stages:
  prepare:
    cmd: python3 src/prepare.py data/raw/train/train.csv
    deps:
    - data/raw/train/train.csv
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  featurize:
    cmd: python3 src/featurization.py data/prepared data/features
    deps:
    - data/prepared
    - src/featurization.py
    params:
    - featurize.max_seq_len
    - featurize.tokenizer
    outs:
    - data/features
  train:
    cmd: python3 src/train.py data/features model.pkl
    deps:
    - data/features
    - src/train.py
    params:
    - train.batch_size
    - train.dropout_rate
    - train.lr
    - train.model_name
    - train.n_epochs
    - train.num_classes
    - train.weight_decay
    outs:
    - model
  evaluate:
    cmd: python3 src/evaluate.py model.pkl data/features
    deps:
    - data/features
    - model/model.pkl
    - src/evaluate.py
    params:
    - evaluate.batch_size
    - evaluate.dropout_rate
    - evaluate.model_name
    - evaluate.num_classes
    outs:
    - eval
